### ISSUE TITLE
ProjectExecutor: Delta creation

### ISSUE THREAD

**Issue by jimmysyl** [ossmeter/ossmeter#53] opened 2015-03-02 20:02 UTC
The following exception is thrown for the following projects: OSSMETER, hippo-cms-angular-core.

The stack trace is:

``` Java
org.eclipse.egit.github.core.client.NoSuchPageException: Not Found (404) at
org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:175) at
org.ossmeter.platform.bugtrackingsystem.github.SimpleIterator.hasNext(SimpleIterator.java:31) at
org.ossmeter.platform.bugtrackingsystem.github.IssueCacheProvider$ItemIterator.hasNext(IssueCache
rovider.java:52) at org.ossmeter.platform.bugtrackingsystem.cache.Cache.cacheItems(Cache.java:106)
at org.ossmeter.platform.bugtrackingsystem.cache.Cache.update(Cache.java:70) at
org.ossmeter.platform.bugtrackingsystem.cache.Cache.getItemsOnDate(Cache.java:49) at
org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getIssues(GitHubManager.java:163) at
org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getDelta(GitHubManager.java:63) at
org.ossmeter.platform.bugtrackingsystem.github.GitHubManager.getDelta(GitHubManager.java:1) at
org.ossmeter.platform.delta.bugtrackingsystem.PlatformBugTrackingSystemManager.getDelta(Platform
ugTrackingSystemManager.java:101) at
org.ossmeter.platform.delta.bugtrackingsystem.BugTrackingSystemProjectDelta
(BugTrackingSystemProjectDelta.java:33) at
org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:70) at
org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127) at
org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109) Caused by:
org.eclipse.egit.github.core.client.RequestException: Not Found (404) at
org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552) at
org.eclipse.egit.github.core.client.GitHubClient.get(GitHubClient.java:740) at
org.eclipse.egit.github.core.client.PageIterator.next(PageIterator.java:173) ... 13 more
```

**Comment by kolovos** [comment] 2015-03-05 14:59
Duplicate of bug #62

**Closed as completed by kolovos** 2015-03-05 14:59 UTC
Labels: bug
