### ISSUE TITLE
Rascal ArithmeticException "Division undefined"

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#44] opened 2015-02-24 11:30 UTC
Bit of a random one, this. The exception below occurred for project modeling-emf-validation, date 20150204. But I suspect the issue wasn't caused by the context  - perhaps Rascal got itself into an invalid state somehow?

``` java
org.rascalmpl.interpreter.control_exceptions.Throw: rascal://Main:126,63: ArithmeticException("Division undefined") at 
org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42) at 
org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:114) at 
java.lang.Throwable.(Throwable.java:265) at 
java.lang.Exception.(Exception.java:66) at 
java.lang.RuntimeException.(RuntimeException.java:62) at 
org.rascalmpl.interpreter.control_exceptions.ControlException.(ControlException.java:25) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:49) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:69) at 
org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.arithmeticException(RuntimeExceptionFactory.java:105) at 
org.rascalmpl.interpreter.result.RealResult.divideReal(RealResult.java:188) at 
org.rascalmpl.interpreter.result.IntegerResult.divideReal(IntegerResult.java:217) at 
org.rascalmpl.interpreter.result.RealResult.divide(RealResult.java:52) at 
org.rascalmpl.semantics.dynamic.Expression$Division.interpret(Expression.java:733) at 
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:486) at 
org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at 
org.rascalmpl.semantics.dynamic.Statement$Return.interpret(Statement.java:782) at 
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at 
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1) at 
org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at 
java.lang.Thread.run(Thread.java:745)
```

**Comment by jurgenvinju** [comment] 2015-02-24 13:37
The bug is throw by:

```
 return round((100.0 * size(range(testedPublicMethods)))/size(allPublicMethods), 0.01);
```

"DivisionUndefined" is related to BigDecimal internal representations of Rascal reals. When the resulting real number is not representable by a finite list of digits and no precision is supported to the internal Java API, this exception may be thrown.

We will hunt for this by identifying a simplified case.

**Comment by jurgenvinju** [comment] 2015-02-24 13:55
```
rascal>(1.0 * 9999999999900000000) / (7 * 9999999999900000000)
real: 0.14285714285714285714
```

not luck so far, but after looking at the code it can also be this:

```
 if (divisor.signum() == 0) {   // x/0
            if (this.signum() == 0)    // 0/0
                throw new ArithmeticException("Division undefined");  // NaN
            throw new ArithmeticException("Division by zero");
        }
```

so hypothesis is `0/0`:

```
rascal>0.0/0.0
|stdin:///|(4,3,<1,4>,<1,7>): ArithmeticException("Division undefined")
```

**Comment by jurgenvinju** [comment] 2015-02-24 14:03
@jrwilliams where is the repo for modeling-emf-validation located? I want to have a look at a checkout of that specific date.

**Comment by jrwilliams** [comment] 2015-02-24 14:05
Should be this one: git://git.eclipse.org/gitroot/emf-validation/org.eclipse.emf.validation.git
-J

**Comment by jurgenvinju** [comment] 2015-02-25 13:00
The `0.0/0` division can only happen if the M3 model contains nu public methods whatsoever in the project. It's good that the exception was thrown. The cause of the empty model is the real problem, but this can not be reproduced as such. Closing the bug for now.

**Closed as completed by jurgenvinju** 2015-02-25 13:00 UTC
Labels: bug, WP3 - Rascal
