### ISSUE TITLE
ProjectExecutor: Delta creation

### ISSUE THREAD

**Issue by jimmysyl** [ossmeter/ossmeter#54] opened 2015-03-02 20:05 UTC
The following exception is thrown for the following projects: BIMserver.

The stack trace is:

``` Java
org.tmatesoft.svn.core.SVNException: svn: E175002: Processing REPORT request response failed: XML
document structures must start and end within the same entity.
(/opensourceBIM/BIMserver/!svn/bc/3029) svn: E175002: REPORT request failed on
'/opensourceBIM/BIMserver/!svn/bc/3029' at
org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:106) at
org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:90) at
org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:758) at
org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:371) at
org.tmatesoft.svn.core.internal.io.dav.http.HTTPConnection.request(HTTPConnection.java:359) at
org.tmatesoft.svn.core.internal.io.dav.DAVConnection.performHttpRequest(DAVConnection.java:707) at
org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doReport(DAVConnection.java:334) at
org.tmatesoft.svn.core.internal.io.dav.DAVConnection.doReport(DAVConnection.java:324) at
org.tmatesoft.svn.core.internal.io.dav.DAVRepository.logImpl(DAVRepository.java:993) at
org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1035) at
org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:940) at
org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:864) at
org.tmatesoft.svn.core.io.SVNRepository.log(SVNRepository.java:1412) at
org.ossmeter.platform.vcs.svn.SvnManager.getRevisionsForDate(SvnManager.java:185) at
org.ossmeter.platform.delta.vcs.PlatformVcsManager.getRevisionsForDate(PlatformVcsManager.java:7
) at org.ossmeter.platform.delta.vcs.VcsProjectDelta.(VcsProjectDelta.java:26) at
org.ossmeter.platform.delta.ProjectDelta.create(ProjectDelta.java:61) at
org.ossmeter.platform.osgi.executors.ProjectExecutor.run(ProjectExecutor.java:127) at
org.ossmeter.platform.osgi.executors.SlaveScheduler$2.run(SlaveScheduler.java:109)
```

**Comment by kolovos** [comment] 2015-03-05 14:58
Duplicate of bug #62

**Closed as completed by kolovos** 2015-03-05 14:58 UTC
Labels: bug
