### ISSUE TITLE
Rascal DateTimePrintingError

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#32] opened 2015-02-13 13:39 UTC
The exception below was thrown for the Eclipse Maven Integration project for the date 20140330.

To reproduce, the project can be imported as follows:

``` java
Platform platform = ...
EclipseProjectImporter im = new EclipseProjectImporter();
im.importProjectByUrl("https://projects.eclipse.org/projects/technology.m2e", platform);
```

The stack trace:

``` java
org.rascalmpl.interpreter.control_exceptions.Throw: rascal://DateTime:555,0: DateTimePrintingError("Cannot print time with format YYYYMMdd") at 
org.rascalmpl.interpreter.control_exceptions.ControlException.reallyFillInStackTrace(ControlException.java:42) at 
org.rascalmpl.interpreter.control_exceptions.Throw.fillInStackTrace(Throw.java:114) at java.lang.Throwable.(Throwable.java:265) at 
java.lang.Exception.(Exception.java:66) at 
java.lang.RuntimeException.(RuntimeException.java:62) at 
org.rascalmpl.interpreter.control_exceptions.ControlException.(ControlException.java:25) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:49) at 
org.rascalmpl.interpreter.control_exceptions.Throw.(Throw.java:69) at 
org.rascalmpl.interpreter.utils.RuntimeExceptionFactory.dateTimePrintingError(RuntimeExceptionFactory.java:262) at 
org.rascalmpl.library.Prelude.printDate(Prelude.java:617) at sun.reflect.GeneratedMethodAccessor213.invoke(Unknown Source) at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at 
org.rascalmpl.interpreter.result.JavaMethod.invoke(JavaMethod.java:233) at 
org.rascalmpl.interpreter.result.JavaMethod.call(JavaMethod.java:167) at 
org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at 
org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at 
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at 
org.rascalmpl.semantics.dynamic.Expression$Addition.interpret(Expression.java:134) at 
org.rascalmpl.semantics.dynamic.Statement$Expression.interpret(Statement.java:364) at 
org.rascalmpl.semantics.dynamic.Statement$Assignment.interpret(Statement.java:204) at 
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at 
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at 
org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at 
org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at 
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at 
org.rascalmpl.semantics.dynamic.Declarator$Default.interpret(Declarator.java:52) at 
org.rascalmpl.semantics.dynamic.LocalVariableDeclaration$Default.interpret(LocalVariableDeclaration.java:35) at 
org.rascalmpl.semantics.dynamic.Statement$VariableDeclaration.interpret(Statement.java:1004) at 
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at 
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:295) at 
org.rascalmpl.interpreter.result.OverloadedFunction.callWith(OverloadedFunction.java:359) at 
org.rascalmpl.interpreter.result.OverloadedFunction.call(OverloadedFunction.java:337) at 
org.rascalmpl.semantics.dynamic.Expression$CallOrTree.interpret(Expression.java:524) at 
org.rascalmpl.semantics.dynamic.Declarator$Default.interpret(Declarator.java:52) at 
org.rascalmpl.semantics.dynamic.LocalVariableDeclaration$Default.interpret(LocalVariableDeclaration.java:35) at 
org.rascalmpl.semantics.dynamic.Statement$VariableDeclaration.interpret(Statement.java:1004) at 
org.rascalmpl.interpreter.result.RascalFunction.runBody(RascalFunction.java:349) at 
org.rascalmpl.interpreter.result.RascalFunction.call(RascalFunction.java:268) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:302) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1) at 
org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
```

**Comment by jurgenvinju** [comment] 2015-03-05 11:39
After some analysis we've come to conclude that this exception can only be thrown if the meta data in the Delta model contains the epoch (0L). The reason why this happens is unclear, it could have to do with conversion problems from SVN to GIT or something. 

The fact that the exception is thrown is still a problem, it should have printed `19700104` anyway.
We will fix this in the Rascal libraries and put a temporary workaround in the delta model construction code.

Note that these fixes will hide the underlying issue of why the epoch (0 time) is there.

**Comment by jurgenvinju** [comment] 2015-03-05 12:06
We now throw an exception at the moment when the meta data is extracted from the Vcs system. This should put us closer to the cause.

**Comment by jurgenvinju** [comment] 2015-03-05 12:07
I can not reproduce the bug for said system and date time; so we will have to wait until it pops up again. In the meantime the specific exception is solved, so I am closing this bug.

**Closed as completed by jurgenvinju** 2015-03-05 12:07 UTC
Labels: bug, WP3 - Rascal

**Comment by jurgenvinju** [comment] 2015-03-26 12:57
See #82
