### ISSUE TITLE
NullPointerException in GitWorkingCopyManager

### ISSUE THREAD

**Issue by jrwilliams** [ossmeter/ossmeter#42] opened 2015-02-24 11:11 UTC
The following exception was thrown for the project drupal on the date 20000518. The root cause seems to come from RascalMetricProvider.java:426: `workingCopyFolders.get(repo.getUrl())`.

The URL of the repo is `"git://git.drupal.org/project/drupal.git"`. I have a folder called "gitgit.drupal.orgprojectdrupal.git", so it appears to exist...?

The stack trace:

``` java
java.lang.NullPointerException at 
org.ossmeter.platform.vcs.workingcopy.git.GitWorkingCopyManager.getDiff(GitWorkingCopyManager.java:73) at 
org.ossmeter.platform.vcs.workingcopy.manager.WorkingCopyFactory.getDiff(WorkingCopyFactory.java:122) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.computeDelta(RascalMetricProvider.java:426) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.callExtractors(RascalMetricProvider.java:472) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.computeAsts(RascalMetricProvider.java:390) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.compute(RascalMetricProvider.java:260) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:206) at 
org.ossmeter.metricprovider.rascal.RascalMetricProvider.measure(RascalMetricProvider.java:1) at 
org.ossmeter.platform.osgi.executors.MetricListExecutor.run(MetricListExecutor.java:130) at 
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at 
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at 
java.lang.Thread.run(Thread.java:745)
```

**Comment by jurgenvinju** [comment] 2015-03-05 14:24
may be duplicate of #62 or at least related. Drupal on either SVN or GIT can not get access to the repository data

**Comment by kolovos** [comment] 2015-03-05 15:33
Obsolete due to #64

**Closed as completed by kolovos** 2015-03-05 15:33 UTC
Labels: bug
